#!/bin/bash

LANG=C
f=$1
t=$2

print_help() {
	echo "Usage: $0 img_file target_dir"
	exit 1
}

[ -z $f ] && print_help
[ -z $t ] && print_help

month=$(ls -l --time-style="+%Y %m" $f | awk '{ print $7 }')
year=$(ls -l --time-style="+%Y %m" $f | awk '{ print $6 }')

[ $? -ne 0 ] && exit 1

[ -z $year ] && exit 1

[ -d $t/$year/$month ] || mkdir -vp $t/$year/$month
mv -v $f $t/$year/$month/
